### ISSUE TITLE
Build failure with Kotlin 1.5.0

### ISSUE THREAD

**Issue by yschimke** [square/kotlinpoet#1078]
See https://github.com/square/okhttp/pull/6664

```
Caused by: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:83)
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.toImmutableKmClass(KotlinPoetMetadata.kt:113)
        at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toImmutableKmClass(MoshiCachedClassInspector.kt:37)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:137)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:114)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
        ... 41 more
```

Reproducable locally.

**Comment by yschimke** [comment]
Haven't investigated yet.

**Comment by JakeWharton** [comment]
Probably just needs a 0.3.0 metadata bump.

**Comment by ZacSweers** [comment]
Something is bringing an old version of KotlinPoet and you just need to force it up to the most recent release or bump the kotlinx-metadata library up to 0.2.0.

**Comment by Egorand** [comment]
Should we bump both kotlin and metadata and release?
