### ISSUE TITLE
Update kotlinx-metadata to 0.3.0

### ISSUE THREAD

**Issue by max-kammerer** [square/kotlinpoet#1114]
Kotlin 1.6 would generate it in 0.3.0 format

**Comment by ZacSweers** [comment]
Send a PR?

**Comment by max-kammerer** [comment]
@ZacSweers Sorry, just found https://github.com/square/kotlinpoet/commit/2c072cfb2d06894a75ef5191315c3c19b561c011

Looks like it's just missed in changelog.md

**Comment by max-kammerer** [comment]
Looks like that my problem linked with Moshi:
```
[ERROR] [kapt] An exception occurred: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
	at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:89)
	at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.toImmutableKmClass(KotlinPoetMetadata.kt:119)
	at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toImmutableKmClass(MoshiCachedClassInspector.kt:37)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:139)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:114)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
```
It depend on previous version of `Poet` (regardless of having explicit dependency to last kotlinx-metadata)

**Comment by ZacSweers** [comment]
Update to Moshi 1.12.0?

**Comment by max-kammerer** [comment]
It's exactly 1.12.0

**Comment by ZacSweers** [comment]
I don't remember offhand what version Moshi is built against but at this point please raise an issue over there as this is the wrong repo for it.

**Comment by max-kammerer** [comment]
Ok, but I need to make additional investigations. There is only 0.3.0 kotlinx-metadata in localrepo, so problem is unclear

**Comment by max-kammerer** [comment]
Filed issue to Moshi with failed project: https://github.com/square/moshi/issues/1368
