### ISSUE TITLE
How to use controlFlow API to check instance type

### ISSUE THREAD

**Issue by Omico** [square/kotlinpoet#1541]
I tried `beginControlFlow("if (target is %T)", Settings::class)`, and it shows the below error.

```
Caused by: java.lang.IllegalArgumentException: expected type but was [Ljava.lang.Object;@62a26875
	at com.squareup.kotlinpoet.CodeBlock$Builder.argToType(CodeBlock.kt:405)
	at com.squareup.kotlinpoet.CodeBlock$Builder.addArgument(CodeBlock.kt:348)
	at com.squareup.kotlinpoet.CodeBlock$Builder.add(CodeBlock.kt:320)
	at com.squareup.kotlinpoet.CodeBlock$Builder.beginControlFlow(CodeBlock.kt:415)
	at com.squareup.kotlinpoet.FunSpec$Builder.beginControlFlow(FunSpec.kt:538)
```

I also tried  `beginControlFlow("if (target is %T)", Settings::class.asClassName())`, and it shows the same error.

**Comment by JakeWharton** [comment]
Seems to work fine in the latest version. Are you on some old version?

**Comment by Omico** [comment]
Thanks, I found the issue. I write an extension function for it. And missing a `*` unconsciously. I really hope kotlinpoet can provide more Kotlin-ify API for us.

```kotlin
inline fun FunSpec.Builder.controlFlow(
    controlFlow: String,
    vararg args: Any,
    block: FunSpec.Builder.() -> Unit,
) {
    beginControlFlow(controlFlow, *args) // was missing * here
    apply(block)
    endControlFlow()
}
```

**Comment by JakeWharton** [comment]
APIs like that prevent the use of `nextControlFlow`. When you need to add an `else` you have to either offer increasing quantities of `body` lambdas or drop back down to the regular `begin`/`end` usage. As we talk about in #62 we're not opposed to doing more for Kotlin authors, but we're not going to just DSL-ify everything for the sake of having a DSL. Builders are still perfectly fine tools to leverage in Kotlin.

**Comment by Omico** [comment]
First of all,

> Builders are still perfectly fine tools to leverage in Kotlin.

I strongly agree. DSL should build upon the builder.

> APIs like that prevent the use of nextControlFlow.

I test it before. Seem it works perfectly. 

I modify a bit of my above extension function. it can also work with builder.

```kotlin
inline fun FunSpec.Builder.controlFlow(
    controlFlow: String,
    vararg args: Any,
    block: FunSpec.Builder.() -> Unit,
): FunSpec.Builder =
    apply {
        beginControlFlow(controlFlow, *args)
        apply(block)
        endControlFlow()
    }
```
```kotlin
    FunSpec.builder("apply")
        .addModifiers(KModifier.OVERRIDE)
        .addParameter("target", ExtensionAware::class)
        .controlFlow("if (target is %T)", Settings::class) {
            addComment("First 1")
            nextControlFlow("else if (target is %T)", Project::class)
            addComment("Second 1")
        }
        .controlFlow("if (target is %T)", Settings::class) {
            addComment("First 2")
            nextControlFlow("else if (target is %T)", Project::class)
            addComment("Second 2")
        }
        .build()
```

```kotlin
 public override fun apply(target: ExtensionAware): Unit {
    if (target is Settings) {
      // First 1
    } else if (target is Project) {
      // Second 1
    }
    if (target is Settings) {
      // First 2
    } else if (target is Project) {
      // Second 2
    }
}
```

**Comment by JakeWharton** [comment]
I mean yes that works, but the presence of a "next control flow" function nested within a "control flow" block is confusing. The DSL in that case should be something like "nextBranch" so as to indicate that it targets the existing control flow, and not somehow deals with the next block.

**Comment by Omico** [comment]
You are right! I took a look at `CodeBlock`. What do you think of this?
```kotlin

interface IfElseStatementsScope {
    fun `if`(condition: String, vararg args: Any, block: IfElseStatementsScope.() -> Unit)
    fun `else`(block: IfElseStatementsScope.() -> Unit)
    fun elseif(condition: String, vararg args: Any, block: IfElseStatementsScope.() -> Unit)
    fun comment(format: String, vararg args: Any)
    // other's are not yet implemented
}

class IfElseStatementsBuilder : IfElseStatementsScope {
    private val body = CodeBlock.builder()

    override fun `if`(condition: String, vararg args: Any, block: IfElseStatementsScope.() -> Unit) {
        body.beginControlFlow("if ($condition)", *args)
        block()
    }

    override fun `else`(block: IfElseStatementsScope.() -> Unit) {
        body.nextControlFlow("else")
        block()
    }

    override fun elseif(condition: String, vararg args: Any, block: IfElseStatementsScope.() -> Unit) {
        body.nextControlFlow("else if ($condition)", *args)
        block()
    }

    override fun comment(format: String, vararg args: Any) {
        body.add("//·${format.replace(' ', '·')}\n", *args)
    }

    fun build(): CodeBlock = with(body) {
        endControlFlow()
        build()
    }
}

fun FunSpec.Builder.ifElseStatements(block: IfElseStatementsScope.() -> Unit): FunSpec.Builder =
    IfElseStatementsBuilder().apply(block).build().let(::addCode)
```
```kotlin
fun main() {
    FunSpec.builder("apply")
        .addModifiers(KModifier.OVERRIDE)
        .addParameter("target", ExtensionAware::class)
        .ifElseStatements {
            `if`("target is %T", Settings::class) {
                comment("hello 1")
            }
            elseif("target is %T", Project::class) {
                comment("hello 2")
            }
            `else` {
                comment("hello 3")
            }
        }
        .ifElseStatements {
            `if`("target is %T", Settings::class) {
                comment("hello 1")
            }
            elseif("target is %T", Project::class) {
                comment("hello 2")
            }
            `else` {
                comment("hello 3")
            }
        }
        .build()
}
```

```
  public override fun apply(target: ExtensionAware): Unit {
    if (target is Settings) {
      // hello 1
    } else if (target is Project) {
      // hello 2
    } else {
      // hello 3
    }
    if (target is Settings) {
      // hello 1
    } else if (target is Project) {
      // hello 2
    } else {
      // hello 3
    }
  }
```

**Comment by Omico** [comment]
Just come up with a more flexible idea.

```
  public override fun apply(target: ExtensionAware): Unit {
    if (target is Settings) {
      // hello 1
    } else if (target is Project) {
      // hello 2
    } else {
      // hello 3
    }
    if (target is Settings) {
      // hello 4
    }
    if (target is Settings) {
      // hello 5
    } else {
      // hello 6
    }
  }
```

```kotlin

fun main() {
    FunSpec.builder("apply")
        .addModifiers(KModifier.OVERRIDE)
        .addParameter("target", ExtensionAware::class)
        .statement {
            `if`("target is %T", Settings::class) {
                comment("hello 1")
            }.elseif("target is %T", Project::class) {
                comment("hello 2")
            }.`else` {
                comment("hello 3")
            }
        }
        .statement {
            `if`("target is %T", Settings::class) {
                comment("hello 4")
            }
        }
        .statement {
            `if`("target is %T", Settings::class) {
                comment("hello 5")
            }.`else` {
                comment("hello 6")
            }
        }
        .build()
}

interface CodeBlockBuilderScope {
    fun build(): CodeBlock
}

interface StatementScope : CodeBlockBuilderScope {
    val body: CodeBlock.Builder
    var builder: StatementBuilderScope
}

interface StatementBuilderScope : CodeBlockBuilderScope

fun StatementScope.`if`(
    condition: String,
    vararg args: Any,
    block: IfElseStatementScope.() -> Unit,
): IfElseStatementScope =
    IfElseStatementBuilder()
        .apply { body.beginControlFlow("if ($condition)", *args) }
        .apply(block)
        .also { builder = it }

class StatementBuilder : StatementScope {
    override val body = CodeBlock.builder()
    override lateinit var builder: StatementBuilderScope

    override fun build(): CodeBlock = with(body) {
        builder.build().let(::add)
        build()
    }
}

fun FunSpec.Builder.statement(block: StatementScope.() -> Unit): FunSpec.Builder =
    StatementBuilder().apply(block).build().let(::addCode)

interface IfElseStatementScope : StatementBuilderScope {
    fun `else`(block: IfElseStatementScope.() -> Unit)
    fun elseif(condition: String, vararg args: Any, block: IfElseStatementScope.() -> Unit): IfElseStatementScope
    fun comment(format: String, vararg args: Any)
}

class IfElseStatementBuilder : IfElseStatementScope {
    private val body = CodeBlock.builder()

    override fun `else`(block: IfElseStatementScope.() -> Unit) {
        body.nextControlFlow("else")
        block()
    }

    override fun elseif(
        condition: String,
        vararg args: Any,
        block: IfElseStatementScope.() -> Unit,
    ): IfElseStatementScope =
        apply {
            body.nextControlFlow("else if ($condition)", *args)
            block()
        }

    override fun comment(format: String, vararg args: Any) {
        body.add("//·${format.replace(' ', '·')}\n", *args)
    }

    override fun build(): CodeBlock = with(body) {
        endControlFlow()
        build()
    }
}
```

**Comment by JakeWharton** [comment]
Pretty good! Although it violates our unwritten rule in that we only model the outer structure of code and not individual language features used in statements.

**Comment by Omico** [comment]
I'm not sure if I understand correctly. Is this what you want?  Also, honestly, things like the if-else statement, when statement, etc., are the basic things in Kotlin. If our lib is named kotlinpoet, why not provide a more comfortable out-of-the-box experience?

```kotlin
fun main() {
    FunSpec.builder("apply")
        .addModifiers(KModifier.OVERRIDE)
        .addParameter("target", ExtensionAware::class)
        .statement {
            controlFlow("if (target is %T)", Settings::class) {
                comment("hello 1")
            }.nextControlFlow("else if (target is %T)", Project::class) {
                comment("hello 2")
            }.nextControlFlow("else") {
                comment("hello 3")
            }
        }
        .statement {
            controlFlow("if (target is %T)", Settings::class) {
                comment("hello 4")
            }
        }
        .statement {
            controlFlow("if (target is %T)", Settings::class) {
                comment("hello 5")
            }.nextControlFlow("else if (target is %T)", Project::class) {
                comment("hello 6")
            }
        }
        .build()
}

fun FunSpec.Builder.statement(block: StatementScope.() -> Unit): FunSpec.Builder =
    StatementBuilder().apply(block).build().let(::addCode)

fun StatementScope.controlFlow(
    controlFlow: String,
    vararg args: Any,
    block: ControlFlowScope.() -> Unit,
): ControlFlowScope =
    ControlFlowBuilder()
        .apply { body.beginControlFlow(controlFlow, *args) }
        .apply(block)
        .also { builder = it }

interface CodeBlockBuilderScope {
    fun build(): CodeBlock
}

interface StatementScope : CodeBlockBuilderScope {
    val body: CodeBlock.Builder
    var builder: StatementBuilderScope
}

interface StatementBuilderScope : CodeBlockBuilderScope

class StatementBuilder : StatementScope {
    override val body = CodeBlock.builder()
    override lateinit var builder: StatementBuilderScope

    override fun build(): CodeBlock = with(body) {
        builder.build().let(::add)
        build()
    }
}

interface ControlFlowScope : StatementBuilderScope {
    fun nextControlFlow(controlFlow: String, vararg args: Any, block: ControlFlowScope.() -> Unit): ControlFlowScope
    fun comment(format: String, vararg args: Any)
}

class ControlFlowBuilder : ControlFlowScope {
    private val body = CodeBlock.builder()

    override fun nextControlFlow(
        controlFlow: String,
        vararg args: Any,
        block: ControlFlowScope.() -> Unit,
    ): ControlFlowScope =
        apply {
            body.nextControlFlow(controlFlow, *args)
            block()
        }

    override fun comment(format: String, vararg args: Any) {
        body.add("//·${format.replace(' ', '·')}\n", *args)
    }

    override fun build(): CodeBlock = with(body) {
        endControlFlow()
        build()
    }
}
```

**Comment by JakeWharton** [comment]
> If our lib is named kotlinpoet, why not provide a more comfortable out-of-the-box experience?

Because it means we don't need to model the complexity and intricacy of what goes on inside method bodies. The name "control flow" comes from JavaPoet and it's less correct to use here because it's built entirely for indent management which happens most with control flow constructs.

We also spend much less time chasing advancements in the Kotlin language. When Kotlin changed to allow you to define a `val` within a `when`'s subject we didn't need to model that and make a new release, for example. If we end up trying to model the entire language the API will actually get far more verbose than it is now with a mostly stringly-typed modeling.

**Comment by Omico** [comment]
I strongly agree with your opinion. I started working on more flexible ways to handle this issue. If you are interested, please take a look at https://github.com/Omico/Gradm/pull/64/files
