### ISSUE TITLE
1.14.0 has breaking ABI changes to documentable and annotatable builders

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#1579]
**Describe the bug**
It seems that the traits (or how they mix with the new JVM default behavior) broke binary compatibility

```
> Task :libraries:summarizer:kspReleaseKotlin FAILED
e: java.lang.NoSuchMethodError: 'com.squareup.kotlinpoet.TypeSpec$Builder com.squareup.kotlinpoet.TypeSpec$Builder.addAnnotation(com.squareup.kotlinpoet.AnnotationSpec)'
        at com.slack.circuit.codegen.CircuitSymbolProcessor.generateFactory(CircuitSymbolProcessorProvider.kt:154)
        at com.slack.circuit.codegen.CircuitSymbolProcessor.process(CircuitSymbolProcessorProvider.kt:111)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
```

**Comment by ZacSweers** [comment]
Looks like we missed it in the code review too :| https://github.com/square/kotlinpoet/pull/1564/files#diff-1f0052aed0b8b0e12d91845dcd2f5dc42aad0e1710363e1ab92b428c92b6c398L921-L925

Guessing we need to explicitly override it. Curious if the jvm default flag plays a role in that

**Comment by ZacSweers** [comment]
This also affects `Documentable`
