### ISSUE TITLE
Applying processor which uses kotlinx-metadata causes NoSuchMethod error for JvmMetadataUtil.Metadata

### ISSUE THREAD

**Issue by dimsuz** [square/kotlinpoet#1600]
**Describe the bug**
I have an annotation processor (kapt-based) which when applied causes kotlinx-metadata's `toKmClass` throw `NoSuchMethod` error

**To Reproduce**
Consuming project has

> Kotlin: 1.8.21

Annotation processor has

> Kotlin: 1.8.21
> Kotlinpoet/Kotlinpoet-metadata: 1.14.2

At the moment I can't provide a sample project unfortunately, because processor is not published on maven yet.

Internal tests in the "processor" IDE project work without issues, but when I publish in maven local + consume, I receieve the error below.

**Expected behavior**
Running kapt-task in the consuming project results in the following exception

```
<gradle tooling stacktrace snipped>
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:90)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:47)
	... 27 more
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoSuchMethodError: 'kotlin.Metadata kotlinx.metadata.jvm.JvmMetadataUtil.Metadata(java.lang.Integer, int[], java.lang.String[], java.lang.String[], java.lang.String, java.lang.String, java.lang.Integer)'
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:997)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:901)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1227)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1340)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1254)
	... 33 more
Caused by: java.lang.NoSuchMethodError: 'kotlin.Metadata kotlinx.metadata.jvm.JvmMetadataUtil.Metadata(java.lang.Integer, int[], java.lang.String[], java.lang.String[], java.lang.String, java.lang.String, java.lang.Integer)'
	at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.asClassHeader(KotlinPoetMetadata.kt:102)
	at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:88)
	at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.toKmClass(KotlinPoetMetadata.kt:118)
	at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.toKmClass(KotlinPoetMetadata.kt:48)
	at ru.dimsuz.vanilla.processor.SourceAnalysisKt.findValidationModelPairs(SourceAnalysis.kt:32)
	at ru.dimsuz.vanilla.processor.VanillaProcessor.process(VanillaProcessor.kt:25)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:985)
	... 37 more
```

**Comment by ZacSweers** [comment]
Without a reproducible example this isn't actionable

**Comment by dimsuz** [comment]
Ok, I'll publish this library and try to come up with the minimal sample project, will post here soon.

**Comment by dimsuz** [comment]
I'll close this for now as it looks like either some gradle caching issue or a specific project setup issue. If I reproduce this on minimal example, I'll reopen with repro project attached.
