### ISSUE TITLE
Can't generate @get:JvmName annotation for property

### ISSUE THREAD

**Issue by andreypfau** [square/kotlinpoet#1773]
**Describe the bug**
```
Exception in thread "main" java.lang.IllegalArgumentException: Can't escape identifier `get:JvmName` because it contains illegal characters: :
	at com.squareup.kotlinpoet.UtilKt.failIfEscapeInvalid(Util.kt:276)
	at com.squareup.kotlinpoet.UtilKt.escapeIfNecessary(Util.kt:286)
	at com.squareup.kotlinpoet.UtilKt.escapeIfNecessary$default(Util.kt:282)
	at com.squareup.kotlinpoet.UtilKt$escapeSegmentsIfNecessary$2.invoke(Util.kt:311)
	at com.squareup.kotlinpoet.UtilKt$escapeSegmentsIfNecessary$2.invoke(Util.kt:311)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at com.squareup.kotlinpoet.UtilKt.escapeSegmentsIfNecessary(Util.kt:311)
	at com.squareup.kotlinpoet.UtilKt.escapeSegmentsIfNecessary$default(Util.kt:309)
	at com.squareup.kotlinpoet.ClassName.emit$kotlinpoet(ClassName.kt:190)
	at com.squareup.kotlinpoet.CodeWriter.emitCode(CodeWriter.kt:305)
	at com.squareup.kotlinpoet.CodeWriter.emitCode$default(CodeWriter.kt:237)
	at com.squareup.kotlinpoet.CodeWriter.emitCode(CodeWriter.kt:235)
	at com.squareup.kotlinpoet.AnnotationSpec.emit$kotlinpoet(AnnotationSpec.kt:58)
	at com.squareup.kotlinpoet.AnnotationSpec.emit$kotlinpoet$default(AnnotationSpec.kt:51)
	at com.squareup.kotlinpoet.CodeWriter.emitAnnotations(CodeWriter.kt:147)
	at com.squareup.kotlinpoet.PropertySpec.emit$kotlinpoet(PropertySpec.kt:80)
	at com.squareup.kotlinpoet.PropertySpec.emit$kotlinpoet$default(PropertySpec.kt:65)
	at com.squareup.kotlinpoet.TypeSpec$emit$1$1.invoke(TypeSpec.kt:203)
	at com.squareup.kotlinpoet.TypeSpec$emit$1$1.invoke(TypeSpec.kt:200)
	at com.squareup.kotlinpoet.ParameterSpecKt.emit(ParameterSpec.kt:247)
	at com.squareup.kotlinpoet.TypeSpec.emit$kotlinpoet(TypeSpec.kt:200)
	at com.squareup.kotlinpoet.TypeSpec.emit$kotlinpoet$default(TypeSpec.kt:109)
	at com.squareup.kotlinpoet.FileSpec.emit(FileSpec.kt:199)
	at com.squareup.kotlinpoet.FileSpec.access$emit(FileSpec.kt:49)
	at com.squareup.kotlinpoet.FileSpec$writeTo$codeWriter$1.invoke(FileSpec.kt:86)
	at com.squareup.kotlinpoet.FileSpec$writeTo$codeWriter$1.invoke(FileSpec.kt:82)
	at com.squareup.kotlinpoet.CodeWriter$Companion.withCollectedImports(CodeWriter.kt:708)
	at com.squareup.kotlinpoet.FileSpec.writeTo(FileSpec.kt:82)
	at com.squareup.kotlinpoet.FileSpec.writeTo(FileSpec.kt:109)
	at com.squareup.kotlinpoet.FileSpec.writeTo(FileSpec.kt:124)
```

**To Reproduce**
```kotlin
AnnotationSpec.builder(ClassName("kotlin","get:JvmName"))
                                    .addMember("%S", "test")
                                    .build()
```
**Expected behavior**
```kotlin
        @get:JvmName("test")
        public val foo: Int,
```

**Comment by Egorand** [comment]
Use the [`AnnotationSpec.Builder.useSiteTarget`](https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-annotation-spec/-builder/use-site-target.html) method to add the `get:` target, it should not be part of the annotation class name:

```kotlin
AnnotationSpec.builder(ClassName("kotlin", "JvmName"))
  .useSiteTarget(UseSiteTarget.GET)
  .addMember("%S", "test")
  .build()
```

**Comment by andreypfau** [comment]
It will be good write about this in documentation

**Comment by ZacSweers** [comment]
It is written about in the documentation: https://square.github.io/kotlinpoet/#annotations:~:text=LogRecord)%3A%20LogReceipt-,KotlinPoet%20supports%20use%2Dsite%20targets%20for%20annotations%3A,-val%20utils%20%3D

**Comment by andreypfau** [comment]
> Use the [`AnnotationSpec.Builder.useSiteTarget`](https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-annotation-spec/-builder/use-site-target.html) method to add the `get:` target, it should not be part of the annotation class name:
> 
> ```kotlin
> AnnotationSpec.builder(ClassName("kotlin", "JvmName"))
>   .useSiteTarget(UseSiteTarget.GET)
>   .addMember("%S", "test")
>   .build()
> ```

Another issue with ClassName: https://github.com/square/kotlinpoet/issues/1775

**Comment by andreypfau** [comment]
> It is written about in the documentation: https://square.github.io/kotlinpoet/#annotations:~:text=LogRecord)%3A%20LogReceipt-,KotlinPoet%20supports%20use%2Dsite%20targets%20for%20annotations%3A,-val%20utils%20%3D

My bad, thank you!
