### ISSUE TITLE
% sign in KDoc causes IllegalArgumentException

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#571]
Test case:
```kotlin
@Test fun percentSignInKDoc() {
  val propSpec = PropertySpec.builder("text", String::class)
      .addKdoc("e.g. \"No limits, free to send and just 2.75% to receive\".")
      .build()
  assertThat(propSpec.toString()).isEqualTo("""
    |/**
    | * e.g. "No limits, free to send and just 2.75% to receive".
    | */
    |val text: kotlin.String
    |""".trimMargin())
}
```

Stack trace:
```kotlin
java.lang.IllegalArgumentException: index 1 for '% ' not in range (received 0 arguments)

	at com.squareup.kotlinpoet.CodeBlock$Builder.add(CodeBlock.kt:306)
	at com.squareup.kotlinpoet.PropertySpec$Builder.addKdoc(PropertySpec.kt:157)
	at com.squareup.kotlinpoet.PropertySpecTest.percentSignInKDoc(PropertySpecTest.kt:319)
```

JavaPoet gets this right, so I guess KotlinPoet should validate/sanitize input as well.

**Comment by Egorand** [comment]
Actually, because JavaPoet uses `$` symbols for placeholders, a `$` symbol in Javadoc will crash it as well.

**Comment by mkobit** [comment]
I ran into something similar and used `%L` for literals in KDoc comments as it seemed deliberate.

**Comment by Egorand** [comment]
@mkobit makes sense!

**Comment by Egorand** [comment]
Yeah, I think `%L` is the right way to go about it. Closing the issue.
