### ISSUE TITLE
Can we expect stable API?

### ISSUE THREAD

**Issue by dimsuz** [square/kotlinpoet#635]
It is the second time we bump into API compatibility errors.

* Our project uses `library1`-`1.0` and `library2`-`1.0`
* `library1`-`1.0` and `library2`-`1.0` use `kotlinpoet`-`1.0.0`, everything's fine
* Now `library1` releases version `1.1` which uses `kotlinpoet`-`1.0.1` (minor release!)

Suddenly we cannot upgrade `library1`, because we get an error in `library2`:

```
e: [kapt] An exception occurred: java.lang.NoSuchMethodError: com.squareup.kotlinpoet.ClassName.asNullable()Lcom/squareup/kotlinpoet/ClassName;
	at com.github.rougsig.actionsdispatcher.processor.ActionElementProvider$Companion.getNullableCommandTypeName(ActionElementProvider.kt:108)
	at com.github.rougsig.actionsdispatcher.processor.ActionElementProvider$Companion.get(ActionElementProvider.kt:45)
	at com.github.rougsig.actionsdispatcher.processor.Processor.process(Processor.kt:52)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:106)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:58)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:223)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:187)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:384)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:70)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:375)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:159)
```

We have to wait until `library2` starts using `kotlin-1.0.1` to be able to upgrade `library1`.

And this happens the second time already. Luckily `library2` is our own, but if this wouldn't be the case, we'd be in bigger trouble.

**Comment by JakeWharton** [comment]
These were removed in an RC, not from a stable release.

**Comment by dimsuz** [comment]
OK, makes sense, I had the feeling that RCs are usually stable API-wise.
