### ISSUE TITLE
Adding a new default parameter to TypeName#copy was a breaking change

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#782]
`tags` was added to the signature of `copy()` below.

```kotlin
abstract fun copy(
    nullable: Boolean = this.isNullable,
    annotations: List<AnnotationSpec> = this.annotations.toList(),
    tags: Map<KClass<*>, Any> = this.tagMap.tags.toMap()
  ): TypeName
```

While this isn't a breaking change for source, it is actually a binary breaking change because the synthetic defaults method signature did change, meaning any previous users of this function would break.

```
e: [kapt] An exception occurred: java.lang.NoSuchMethodError: com.squareup.kotlinpoet.TypeName.copy$default(Lcom/squareup/kotlinpoet/TypeName;ZLjava/util/List;ILjava/lang/Object;)Lcom/squareup/kotlinpoet/TypeName;
        at com.squareup.moshi.kotlin.codegen.MetadataKt.asTypeName(metadata.kt:205)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.declaredProperties(metadata.kt:381)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:322)

```

Possible solutions are to revert the change or add an overload of copy

**Comment by ZacSweers** [comment]
ninja edit: or maybe @JvmOverloads
