### ISSUE TITLE
Circular Generic Type -- Metadata: java.lang.IllegalStateException: No type argument found for 0! 

### ISSUE THREAD

**Issue by Wasabi375** [square/kotlinpoet#812]
I tried to reproduce this bug https://github.com/square/moshi/issues/955 directly with kotlinpoet:
By adding this to KotlinPoetMetadataSpecTest
```kotlin
class Asset<A: Asset<A>>
class AssetMetaData<A: Asset<A>>

@Test
fun noTypeArgumentFound() {
  AssetMetaData::class.toTypeSpecWithTestHandler()
}
```
I got the following error
```
java.lang.IllegalStateException: No type argument found for 0!

	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt:198)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:84)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:62)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:81)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeVariableName(KmTypes.kt:161)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver(KotlinPoetMetadataSpecs.kt:201)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver$default(KotlinPoetMetadataSpecs.kt:192)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:211)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:138)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:132)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:131)
```
which matches my error in moshi. As far as I can tell this is due to the circular generic type definition.

**Comment by Wasabi375** [comment]
some further testing on my part shows that this code is enough to reproduce the error
```kotlin
class Asset<A: Asset<A>>
@Test
fun noTypeArgumentFound() {
  Asset::class.toTypeSpecWithTestHandler()
}
```

**Comment by Wasabi375** [comment]
Looking more into the problem, it seems like kotlinpoet specs currently don't allow for a class like this. At least I can't figure out how to create such a class, both programmaticly from the metadata but also using the builder API.

**Comment by Egorand** [comment]
Here's the builders version:
```kotlin
@Test fun selfType() {
  val asset = ClassName("", "Asset")
  val a = TypeVariableName("A")
  val assetOfA = asset.parameterizedBy(a)
  val aWithAssetOfABounds = a.copy(bounds = listOf(assetOfA))

  val selfType = TypeSpec.classBuilder(asset)
      .addTypeVariable(aWithAssetOfABounds)
      .build()
  assertThat(selfType.toString().trim()).isEqualTo("class Asset<A : Asset<A>>")
}
```

**Comment by ZacSweers** [comment]
The builder approach works fine. This is a bug in metadata parsing with backward type variable refs. I’ll take a look

**Comment by ZacSweers** [comment]
Opened a PR here: #813
