### ISSUE TITLE
Inline function with reified type parameter raises NoSuchElementException

### ISSUE THREAD

**Issue by mannodermaus** [square/kotlinpoet#829]
Related issue on Moshi:
https://github.com/square/moshi/issues/1008

---

The following model class definition fails with Moshi 1.9.0 (using KotlinPoet 1.4.3) and above:

```kotlin
@JsonClass(generateAdapter = true)
data class Model(@Json(name = "id") val id: String) {
    inline fun <reified T> inlineMethod(named: String): T? = null
}
```

The fields on the class & the body of its inline function are irrelevant - instead, it seems like the presence of the `reified` keyword will cause Moshi's codegen, backed by KotlinPoet, to fail with the following message:

```
e: [kapt] An exception occurred: java.util.NoSuchElementException: Key 0 is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toFunSpec(KotlinPoetMetadataSpecs.kt:543)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.access$toFunSpec(KotlinPoetMetadataSpecs.kt:1)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$26.invoke(KotlinPoetMetadataSpecs.kt:429)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$26.invoke(KotlinPoetMetadataSpecs.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at com.squareup.kotlinpoet.TypeSpec$Builder.addFunctions(TypeSpec.kt:786)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:403)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:171)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:153)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:133)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:107)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
(More kapt stuff below this line...)
```

As a workaround, the `reified inline fun` can be defined outside of the model class, as an extension function:

```kotlin
@JsonClass(generateAdapter = true)
data class Model(@Json(name = "id") val id: String)

// This works
inline fun <reified T> Model.inlineMethod(named: String): T? = null
```

The problem remains when using the latest `1.5.0-SNAPSHOT` of KotlinPoet instead.

**Comment by ZacSweers** [comment]
Dug into this a bit, I believe this is an issue only in `ElementsClassInspector` and is happening because reified methods are `synthetic`, thus not present in the `MethodData`.

**Comment by ZacSweers** [comment]
PR #830

**Comment by mannodermaus** [comment]
@ZacSweers, thanks for the quick work! I'm trying to verify the fix on my environment, though I'm having trouble setting up the environment correctly, it seems like - compilation still fails with the same message. Here's my `build.gradle`'s `dependencies` block:

```kotlin
dependencies {
    implementation("com.squareup.moshi:moshi:1.10.0-SNAPSHOT")
    kapt("com.squareup.moshi:moshi-kotlin-codegen:1.10.0-SNAPSHOT") {
        // Exclude transitive KotlinPoet as it is redefined below
        exclude(module = "kotlinpoet")
        exclude(module = "kotlinpoet-metadata")
        exclude(module = "kotlinpoet-metadata-specs")
    }

    // Trying to pin the latest snapshots directly. It also doesn't work if using 1.5.0-SNAPSHOT
    kapt("com.squareup:kotlinpoet-metadata-specs:1.5.0-20191108.130913-19")
    kapt("com.squareup:kotlinpoet-metadata:1.5.0-20191108.130908-19")
    kapt("com.squareup:kotlinpoet:1.5.0-20191108.130837-19")
}
```

The output of `gradlew dependencies` yields the following for the `kapt` configuration:

```
kapt
+--- com.squareup.moshi:moshi-kotlin-codegen:1.10.0-SNAPSHOT
|    +--- com.squareup.moshi:moshi:1.10.0-SNAPSHOT
|    |    \--- com.squareup.okio:okio:1.16.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50
|         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
|         \--- org.jetbrains:annotations:13.0
+--- com.squareup:kotlinpoet-metadata-specs:1.5.0-20191108.130913-19
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
|    +--- com.squareup:kotlinpoet:1.5.0-SNAPSHOT -> 1.5.0-20191108.130837-19
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.50
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
|    \--- com.squareup:kotlinpoet-metadata:1.5.0-SNAPSHOT -> 1.5.0-20191108.130908-19
|         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 (*)
|         \--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.1.0
|              \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.3.50 (*)
+--- com.squareup:kotlinpoet-metadata:1.5.0-20191108.130908-19 (*)
\--- com.squareup:kotlinpoet:1.5.0-20191108.130837-19 (*)
```

From what I can see, `com.squareup:kotlinpoet-metadata-specs:1.5.0-20191108.130913-19` seems to include the changeset introduced in #830, so not sure if there might be more to this case than initially thought.

<img width="1233" alt="Screen Shot 2019-11-08 at 15 47 26" src="https://user-images.githubusercontent.com/3897705/68485213-237fe180-023f-11ea-96f5-1aaf088ef37d.png">

**Comment by ZacSweers** [comment]
Kotlinpoet metadata is shaded in Moshi since it's an unstable API, we'll
need to update Moshi to this first.

**Comment by mannodermaus** [comment]
That explains the package name in the stack trace. Got it!
